apiVersion: v1
kind: Service
metadata:
  name: {{ include "iyp.fullname" . }}
  labels:
    {{- include "iyp.labels" . | nindent 4 }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.metallb.pool }}
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.metallb.pool }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.ports.bolt }}
      targetPort: bolt
      protocol: TCP
      name: bolt
  selector:
    {{- include "iyp.selectorLabels" . | nindent 4 }}